/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package groceryexpress;

import org.junit.jupiter.api.Test;

class CLITest {
    @Test void testCLI() {
//        CLI cli = new CLI();
    }
}
